# -*- coding: utf-8 -*-
"""survey.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xRnGzHwo0RSkREru2GUSS3WOkh1WSxna
"""

import streamlit as st
import random

# Listado de muestras
muestras = ['Muestra 1', 'Muestra 2', 'Muestra 3', 'Muestra 4', 'Muestra 5',
            'Muestra 6', 'Muestra 7', 'Muestra 8', 'Muestra 9', 'Muestra 10']

# Estado para llevar el seguimiento de las selecciones
if 'ganadora' not in st.session_state:
    st.session_state.ganadora = None
if 'indice' not in st.session_state:
    st.session_state.indice = 1
if 'historial' not in st.session_state:
    st.session_state.historial = []

# Función para actualizar la encuesta
def actualizar_encuesta(ganadora):
    if st.session_state.indice < len(muestras):
        st.session_state.historial.append((ganadora, muestras[st.session_state.indice]))
        st.session_state.indice += 1
        st.session_state.ganadora = ganadora
    else:
        st.session_state.historial.append((ganadora, "Final"))

# Título y descripción
st.title("Encuesta de Muestras")
st.write("Selecciona la muestra que prefieras entre las dos opciones.")

# Mostrar las dos opciones
if st.session_state.indice < len(muestras):
    opcion_1 = st.session_state.ganadora or muestras[0]
    opcion_2 = muestras[st.session_state.indice]
    st.write(f"Opción 1: {opcion_1}")
    st.write(f"Opción 2: {opcion_2}")
    
    col1, col2 = st.columns(2)
    
    with col1:
        if st.button(f"Seleccionar {opcion_1}"):
            actualizar_encuesta(opcion_1)
    
    with col2:
        if st.button(f"Seleccionar {opcion_2}"):
            actualizar_encuesta(opcion_2)
else:
    st.write(f"La muestra ganadora es: {st.session_state.ganadora}")

# Mostrar el historial de comparaciones
st.write("Historial de comparaciones:")
for par in st.session_state.historial:
    st.write(f"Comparado: {par[0]} vs {par[1]}")
